### ISSUE TITLE
Continous usage of config files

### ISSUE THREAD

**Issue by GeneSysTobiasWagner** [GeneSysElektronik/adma_ros_driver#15]
Some tools have config files and some not. It might be good to integrate a config file for every tool. Idea was, to put parameters, that have to be adapted very often, into the config files and rarely adapted parameters into the launch file.

**Comment by rschilli-dev** [comment]
Done for GSDA. In case of `bag2gsdb` it would be not very clean to move the param(s) into a yaml since some params are re-used for mulitple nodes, therefore it would need some additional yaml-handling code in the launch file to read the config.yaml and extract the desired params for each node. So, to reduce complexity in launch file this feature is (currently) not solved for the `bag2gsdb` tool, but all other tools/launch files are cleaned up by introducing a config.yaml.
